# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='photo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
