# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_app', '0002_auto_20180227_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='photo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
