# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_app', '0003_sites_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sites',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
