# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_app', '0004_auto_20180228_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='status_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
