# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM_app', '0006_contractors_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesmaterials',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
